--
-- PostgreSQL database dump
--

--
-- Name: groups; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA groups;


ALTER SCHEMA groups OWNER TO max_superuser;

--
-- Name: personalities; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA personalities;


ALTER SCHEMA personalities OWNER TO max_superuser;

--
-- Name: schedules; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA schedules;


ALTER SCHEMA schedules OWNER TO max_superuser;

--
-- Name: subjects; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA subjects;


ALTER SCHEMA subjects OWNER TO max_superuser;

--
-- Name: universities; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA universities;


ALTER SCHEMA universities OWNER TO max_superuser;

--
-- Name: users; Type: SCHEMA; Schema: -; Owner: max_superuser
--

CREATE SCHEMA users;


ALTER SCHEMA users OWNER TO max_superuser;

--
-- Name: day_type; Type: TYPE; Schema: schedules; Owner: max_superuser
--

CREATE TYPE schedules.day_type AS ENUM (
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday'
);


ALTER TYPE schedules.day_type OWNER TO max_superuser;

--
-- Name: interval_type; Type: TYPE; Schema: schedules; Owner: max_superuser
--

CREATE TYPE schedules.interval_type AS ENUM (
    'every week',
    'every two week',
    'every month'
);


ALTER TYPE schedules.interval_type OWNER TO max_superuser;

--
-- Name: subject_type; Type: TYPE; Schema: subjects; Owner: max_superuser
--

CREATE TYPE subjects.subject_type AS ENUM (
    'lecture',
    'practice',
    'labwork',
    'seminar'
);


ALTER TYPE subjects.subject_type OWNER TO max_superuser;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: course_groups; Type: TABLE; Schema: groups; Owner: max_superuser
--

CREATE TABLE groups.course_groups (
    id bigint NOT NULL,
    name character varying(125) NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE groups.course_groups OWNER TO max_superuser;

--
-- Name: course_groups_id_seq; Type: SEQUENCE; Schema: groups; Owner: max_superuser
--

ALTER TABLE groups.course_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME groups.course_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elective_groups; Type: TABLE; Schema: groups; Owner: max_superuser
--

CREATE TABLE groups.elective_groups (
    id bigint NOT NULL,
    name character varying(125) NOT NULL,
    semester_id bigint NOT NULL,
    university_subject_id bigint NOT NULL
);


ALTER TABLE groups.elective_groups OWNER TO max_superuser;

--
-- Name: elective_groups_id_seq; Type: SEQUENCE; Schema: groups; Owner: max_superuser
--

ALTER TABLE groups.elective_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME groups.elective_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students_elective_groups; Type: TABLE; Schema: groups; Owner: max_superuser
--

CREATE TABLE groups.students_elective_groups (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    elective_group_id bigint NOT NULL
);


ALTER TABLE groups.students_elective_groups OWNER TO max_superuser;

--
-- Name: students_elective_groups_id_seq; Type: SEQUENCE; Schema: groups; Owner: max_superuser
--

ALTER TABLE groups.students_elective_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME groups.students_elective_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: administrations; Type: TABLE; Schema: personalities; Owner: max_superuser
--

CREATE TABLE personalities.administrations (
    id bigint NOT NULL,
    max_user_id bigint NOT NULL,
    university_id bigint NOT NULL,
    faculty_id bigint
);


ALTER TABLE personalities.administrations OWNER TO max_superuser;

--
-- Name: administrations_id_seq; Type: SEQUENCE; Schema: personalities; Owner: max_superuser
--

ALTER TABLE personalities.administrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME personalities.administrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: personalities; Owner: max_superuser
--

CREATE TABLE personalities.students (
    id bigint NOT NULL,
    max_user_id bigint NOT NULL,
    is_graduated boolean DEFAULT false NOT NULL,
    university_deparment_id bigint NOT NULL,
    course_group_id bigint
);


ALTER TABLE personalities.students OWNER TO max_superuser;

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: personalities; Owner: max_superuser
--

ALTER TABLE personalities.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME personalities.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachers; Type: TABLE; Schema: personalities; Owner: max_superuser
--

CREATE TABLE personalities.teachers (
    id bigint NOT NULL,
    max_user_id bigint NOT NULL,
    description character varying(1500)
);


ALTER TABLE personalities.teachers OWNER TO max_superuser;

--
-- Name: teachers_id_seq; Type: SEQUENCE; Schema: personalities; Owner: max_superuser
--

ALTER TABLE personalities.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME personalities.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classes; Type: TABLE; Schema: schedules; Owner: max_superuser
--

CREATE TABLE schedules.classes (
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    pair_number integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    CONSTRAINT check_name CHECK (((pair_number > 0) AND (pair_number < 15))),
    CONSTRAINT check_name_2 CHECK ((start_time < end_time))
);


ALTER TABLE schedules.classes OWNER TO max_superuser;

--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: schedules; Owner: max_superuser
--

ALTER TABLE schedules.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schedules.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups_schedules; Type: TABLE; Schema: schedules; Owner: max_superuser
--

CREATE TABLE schedules.groups_schedules (
    id bigint NOT NULL,
    course_group_subjet_id bigint,
    elective_group_subject_id bigint,
    day schedules.day_type NOT NULL,
    class_id bigint NOT NULL,
    room_id bigint NOT NULL,
    "interval" schedules.interval_type NOT NULL,
    CONSTRAINT check_name CHECK (((course_group_subjet_id IS NOT NULL) OR (elective_group_subject_id IS NOT NULL)))
);


ALTER TABLE schedules.groups_schedules OWNER TO max_superuser;

--
-- Name: groups_schedules_id_seq; Type: SEQUENCE; Schema: schedules; Owner: max_superuser
--

ALTER TABLE schedules.groups_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schedules.groups_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: schedules; Owner: max_superuser
--

CREATE TABLE schedules.rooms (
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    room character varying(125) NOT NULL
);


ALTER TABLE schedules.rooms OWNER TO max_superuser;

--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: schedules; Owner: max_superuser
--

ALTER TABLE schedules.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schedules.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_group_subjects; Type: TABLE; Schema: subjects; Owner: max_superuser
--

CREATE TABLE subjects.course_group_subjects (
    id bigint NOT NULL,
    course_group_id bigint NOT NULL,
    course_semester_subject_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    subject_type subjects.subject_type NOT NULL
);


ALTER TABLE subjects.course_group_subjects OWNER TO max_superuser;

--
-- Name: course_group_subjects_id_seq; Type: SEQUENCE; Schema: subjects; Owner: max_superuser
--

ALTER TABLE subjects.course_group_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME subjects.course_group_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_semester_subjects; Type: TABLE; Schema: subjects; Owner: max_superuser
--

CREATE TABLE subjects.course_semester_subjects (
    id bigint NOT NULL,
    semester_id bigint NOT NULL,
    course_id bigint NOT NULL,
    university_subject_id bigint NOT NULL,
    is_elective boolean DEFAULT false NOT NULL,
    required_hours_by_semester integer
);


ALTER TABLE subjects.course_semester_subjects OWNER TO max_superuser;

--
-- Name: course_semester_subjects_id_seq; Type: SEQUENCE; Schema: subjects; Owner: max_superuser
--

ALTER TABLE subjects.course_semester_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME subjects.course_semester_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: elective_group_subjects; Type: TABLE; Schema: subjects; Owner: max_superuser
--

CREATE TABLE subjects.elective_group_subjects (
    id bigint NOT NULL,
    elective_group_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    subject_type subjects.subject_type NOT NULL
);


ALTER TABLE subjects.elective_group_subjects OWNER TO max_superuser;

--
-- Name: elective_group_subjects_id_seq; Type: SEQUENCE; Schema: subjects; Owner: max_superuser
--

ALTER TABLE subjects.elective_group_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME subjects.elective_group_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: university_subjects; Type: TABLE; Schema: subjects; Owner: max_superuser
--

CREATE TABLE subjects.university_subjects (
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    name character varying(125) NOT NULL
);


ALTER TABLE subjects.university_subjects OWNER TO max_superuser;

--
-- Name: university_subjects_id_seq; Type: SEQUENCE; Schema: subjects; Owner: max_superuser
--

ALTER TABLE subjects.university_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME subjects.university_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cities; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.cities (
    id bigint NOT NULL,
    name character varying(125) NOT NULL
);


ALTER TABLE universities.cities OWNER TO max_superuser;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.cities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.courses (
    id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    university_department_id bigint NOT NULL
);


ALTER TABLE universities.courses OWNER TO max_superuser;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.departments (
    id bigint NOT NULL,
    name character varying(125) NOT NULL,
    code character varying(125) NOT NULL
);


ALTER TABLE universities.departments OWNER TO max_superuser;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faculties; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.faculties (
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    name character varying(125) NOT NULL
);


ALTER TABLE universities.faculties OWNER TO max_superuser;

--
-- Name: faculties_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.faculties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.faculties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: semesters; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.semesters (
    id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    university_id bigint NOT NULL
);


ALTER TABLE universities.semesters OWNER TO max_superuser;

--
-- Name: semesters_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.semesters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.semesters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: universities_data; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.universities_data (
    id bigint NOT NULL,
    name text NOT NULL,
    short_name text,
    city_id bigint NOT NULL,
    site_url text,
    description text
);


ALTER TABLE universities.universities_data OWNER TO max_superuser;

--
-- Name: TABLE universities_data; Type: COMMENT; Schema: universities; Owner: max_superuser
--

COMMENT ON TABLE universities.universities_data IS 'information about university';


--
-- Name: COLUMN universities_data.name; Type: COMMENT; Schema: universities; Owner: max_superuser
--

COMMENT ON COLUMN universities.universities_data.name IS 'full name of university';


--
-- Name: universities_data_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.universities_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.universities_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: university_departments; Type: TABLE; Schema: universities; Owner: max_superuser
--

CREATE TABLE universities.university_departments (
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    faculty_id bigint NOT NULL,
    department_id bigint NOT NULL,
    alias_name character varying(125)
);


ALTER TABLE universities.university_departments OWNER TO max_superuser;

--
-- Name: university_departments_id_seq; Type: SEQUENCE; Schema: universities; Owner: max_superuser
--

ALTER TABLE universities.university_departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME universities.university_departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: max_users_data; Type: TABLE; Schema: users; Owner: max_superuser
--

CREATE TABLE users.max_users_data (
    id bigint NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50),
    username text,
    is_bot boolean DEFAULT false NOT NULL,
    last_activity bigint,
    description character varying(16000),
    avatar_url text,
    full_avatar_url text
);


ALTER TABLE users.max_users_data OWNER TO max_superuser;

--
-- Name: TABLE max_users_data; Type: COMMENT; Schema: users; Owner: max_superuser
--

COMMENT ON TABLE users.max_users_data IS 'max_users_data';


--
-- Name: COLUMN max_users_data.id; Type: COMMENT; Schema: users; Owner: max_superuser
--

COMMENT ON COLUMN users.max_users_data.id IS 'MAX ID';


--
-- Name: course_groups course_groups_name_course_id_ukey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.course_groups
    ADD CONSTRAINT course_groups_name_course_id_ukey UNIQUE (name, course_id);


--
-- Name: course_groups course_groups_pkey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.course_groups
    ADD CONSTRAINT course_groups_pkey PRIMARY KEY (id);


--
-- Name: elective_groups elective_groups_pkey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.elective_groups
    ADD CONSTRAINT elective_groups_pkey PRIMARY KEY (id);


--
-- Name: elective_groups elective_groups_semester_subject_ukey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.elective_groups
    ADD CONSTRAINT elective_groups_semester_subject_ukey UNIQUE (semester_id, university_subject_id);


--
-- Name: students_elective_groups students_elective_groups_pkey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.students_elective_groups
    ADD CONSTRAINT students_elective_groups_pkey PRIMARY KEY (id);


--
-- Name: students_elective_groups students_elective_groups_students_groups_ukey; Type: CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.students_elective_groups
    ADD CONSTRAINT students_elective_groups_students_groups_ukey UNIQUE (student_id, elective_group_id);


--
-- Name: administrations administrations_pkey; Type: CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.administrations
    ADD CONSTRAINT administrations_pkey PRIMARY KEY (id);


--
-- Name: students students_pk; Type: CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.students
    ADD CONSTRAINT students_pk UNIQUE (max_user_id, course_group_id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: teachers teachers_max_user_id_ukey; Type: CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.teachers
    ADD CONSTRAINT teachers_max_user_id_ukey UNIQUE (max_user_id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: classes classes_pk; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.classes
    ADD CONSTRAINT classes_pk UNIQUE (university_id, pair_number);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: groups_schedules groups_schedules_pk; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_pk UNIQUE (day, class_id, "interval");


--
-- Name: groups_schedules groups_schedules_pkey; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pk; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.rooms
    ADD CONSTRAINT rooms_pk UNIQUE (university_id, room);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: course_group_subjects course_group_subjects_pk; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_group_subjects
    ADD CONSTRAINT course_group_subjects_pk UNIQUE (course_group_id, course_semester_subject_id, teacher_id, subject_type);


--
-- Name: course_group_subjects course_group_subjects_pkey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_group_subjects
    ADD CONSTRAINT course_group_subjects_pkey PRIMARY KEY (id);


--
-- Name: course_semester_subjects course_semester_subjects_pkey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_semester_subjects
    ADD CONSTRAINT course_semester_subjects_pkey PRIMARY KEY (id);


--
-- Name: course_semester_subjects course_semester_subjects_semester_course_subject_ukey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_semester_subjects
    ADD CONSTRAINT course_semester_subjects_semester_course_subject_ukey UNIQUE (semester_id, course_id, university_subject_id);


--
-- Name: elective_group_subjects elective_group_subjects_pk; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.elective_group_subjects
    ADD CONSTRAINT elective_group_subjects_pk UNIQUE (elective_group_id, teacher_id, subject_type);


--
-- Name: elective_group_subjects elective_group_subjects_pkey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.elective_group_subjects
    ADD CONSTRAINT elective_group_subjects_pkey PRIMARY KEY (id);


--
-- Name: university_subjects university_subjects_pkey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.university_subjects
    ADD CONSTRAINT university_subjects_pkey PRIMARY KEY (id);


--
-- Name: university_subjects university_subjects_university_name_ukey; Type: CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.university_subjects
    ADD CONSTRAINT university_subjects_university_name_ukey UNIQUE (university_id, name);


--
-- Name: cities cities_name_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.cities
    ADD CONSTRAINT cities_name_ukey UNIQUE (name);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: courses courses_start_end_university_department_id; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.courses
    ADD CONSTRAINT courses_start_end_university_department_id UNIQUE (start_date, end_date, university_department_id);


--
-- Name: departments departments_name_code_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.departments
    ADD CONSTRAINT departments_name_code_ukey UNIQUE (name, code);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: faculties faculties_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.faculties
    ADD CONSTRAINT faculties_pkey PRIMARY KEY (id);


--
-- Name: faculties faculties_university_name_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.faculties
    ADD CONSTRAINT faculties_university_name_ukey UNIQUE (university_id, name);


--
-- Name: semesters semesters_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.semesters
    ADD CONSTRAINT semesters_pkey PRIMARY KEY (id);


--
-- Name: universities_data universities_data_name_city_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.universities_data
    ADD CONSTRAINT universities_data_name_city_ukey UNIQUE (name, city_id);


--
-- Name: universities_data universities_data_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.universities_data
    ADD CONSTRAINT universities_data_pkey PRIMARY KEY (id);


--
-- Name: universities_data universities_data_short_name_city_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.universities_data
    ADD CONSTRAINT universities_data_short_name_city_ukey UNIQUE (short_name, city_id);


--
-- Name: university_departments university_departments_pkey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.university_departments
    ADD CONSTRAINT university_departments_pkey PRIMARY KEY (id);


--
-- Name: university_departments university_departments_ukey; Type: CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.university_departments
    ADD CONSTRAINT university_departments_ukey UNIQUE (university_id, department_id);


--
-- Name: max_users_data max_users_data_pkey; Type: CONSTRAINT; Schema: users; Owner: max_superuser
--

ALTER TABLE ONLY users.max_users_data
    ADD CONSTRAINT max_users_data_pkey PRIMARY KEY (id);


--
-- Name: course_groups course_groups_courses_id_fk; Type: FK CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.course_groups
    ADD CONSTRAINT course_groups_courses_id_fk FOREIGN KEY (course_id) REFERENCES universities.courses(id);


--
-- Name: elective_groups elective_groups_semesters_id_fk; Type: FK CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.elective_groups
    ADD CONSTRAINT elective_groups_semesters_id_fk FOREIGN KEY (semester_id) REFERENCES universities.semesters(id);


--
-- Name: elective_groups elective_groups_university_subjects_id_fk; Type: FK CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.elective_groups
    ADD CONSTRAINT elective_groups_university_subjects_id_fk FOREIGN KEY (university_subject_id) REFERENCES subjects.university_subjects(id);


--
-- Name: students_elective_groups students_elective_groups_elective_groups_id_fk; Type: FK CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.students_elective_groups
    ADD CONSTRAINT students_elective_groups_elective_groups_id_fk FOREIGN KEY (elective_group_id) REFERENCES groups.elective_groups(id);


--
-- Name: students_elective_groups students_elective_groups_students_id_fk; Type: FK CONSTRAINT; Schema: groups; Owner: max_superuser
--

ALTER TABLE ONLY groups.students_elective_groups
    ADD CONSTRAINT students_elective_groups_students_id_fk FOREIGN KEY (student_id) REFERENCES personalities.students(id);


--
-- Name: administrations administrations_faculties_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.administrations
    ADD CONSTRAINT administrations_faculties_id_fk FOREIGN KEY (faculty_id) REFERENCES universities.faculties(id);


--
-- Name: administrations administrations_max_users_data_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.administrations
    ADD CONSTRAINT administrations_max_users_data_id_fk FOREIGN KEY (max_user_id) REFERENCES users.max_users_data(id);


--
-- Name: administrations administrations_universities_data_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.administrations
    ADD CONSTRAINT administrations_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);


--
-- Name: students students_course_groups_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.students
    ADD CONSTRAINT students_course_groups_id_fk FOREIGN KEY (course_group_id) REFERENCES groups.course_groups(id);


--
-- Name: students students_max_users_data_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.students
    ADD CONSTRAINT students_max_users_data_id_fk FOREIGN KEY (max_user_id) REFERENCES users.max_users_data(id);


--
-- Name: students students_university_departments_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.students
    ADD CONSTRAINT students_university_departments_id_fk FOREIGN KEY (university_deparment_id) REFERENCES universities.university_departments(id);


--
-- Name: teachers teachers_max_users_data_id_fk; Type: FK CONSTRAINT; Schema: personalities; Owner: max_superuser
--

ALTER TABLE ONLY personalities.teachers
    ADD CONSTRAINT teachers_max_users_data_id_fk FOREIGN KEY (max_user_id) REFERENCES users.max_users_data(id);


--
-- Name: classes classes_universities_data_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.classes
    ADD CONSTRAINT classes_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);


--
-- Name: groups_schedules groups_schedules_classes_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_classes_id_fk FOREIGN KEY (class_id) REFERENCES schedules.classes(id);


--
-- Name: groups_schedules groups_schedules_course_group_subjects_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_course_group_subjects_id_fk FOREIGN KEY (course_group_subjet_id) REFERENCES subjects.course_group_subjects(id);


--
-- Name: groups_schedules groups_schedules_elective_group_subjects_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_elective_group_subjects_id_fk FOREIGN KEY (elective_group_subject_id) REFERENCES subjects.elective_group_subjects(id);


--
-- Name: groups_schedules groups_schedules_rooms_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.groups_schedules
    ADD CONSTRAINT groups_schedules_rooms_id_fk FOREIGN KEY (room_id) REFERENCES schedules.rooms(id);


--
-- Name: rooms rooms_universities_data_id_fk; Type: FK CONSTRAINT; Schema: schedules; Owner: max_superuser
--

ALTER TABLE ONLY schedules.rooms
    ADD CONSTRAINT rooms_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);


--
-- Name: course_group_subjects course_group_subjects_course_groups_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_group_subjects
    ADD CONSTRAINT course_group_subjects_course_groups_id_fk FOREIGN KEY (course_group_id) REFERENCES groups.course_groups(id);


--
-- Name: course_group_subjects course_group_subjects_course_semester_subjects_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_group_subjects
    ADD CONSTRAINT course_group_subjects_course_semester_subjects_id_fk FOREIGN KEY (course_semester_subject_id) REFERENCES subjects.course_semester_subjects(id);


--
-- Name: course_group_subjects course_group_subjects_teachers_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_group_subjects
    ADD CONSTRAINT course_group_subjects_teachers_id_fk FOREIGN KEY (teacher_id) REFERENCES personalities.teachers(id);


--
-- Name: course_semester_subjects course_semester_subjects_courses_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_semester_subjects
    ADD CONSTRAINT course_semester_subjects_courses_id_fk FOREIGN KEY (course_id) REFERENCES universities.courses(id);


--
-- Name: course_semester_subjects course_semester_subjects_semesters_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_semester_subjects
    ADD CONSTRAINT course_semester_subjects_semesters_id_fk FOREIGN KEY (semester_id) REFERENCES universities.semesters(id);


--
-- Name: course_semester_subjects course_semester_subjects_university_subjects_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.course_semester_subjects
    ADD CONSTRAINT course_semester_subjects_university_subjects_id_fk FOREIGN KEY (university_subject_id) REFERENCES subjects.university_subjects(id);


--
-- Name: elective_group_subjects elective_group_subjects_elective_groups_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.elective_group_subjects
    ADD CONSTRAINT elective_group_subjects_elective_groups_id_fk FOREIGN KEY (elective_group_id) REFERENCES groups.elective_groups(id);


--
-- Name: elective_group_subjects elective_group_subjects_teachers_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.elective_group_subjects
    ADD CONSTRAINT elective_group_subjects_teachers_id_fk FOREIGN KEY (teacher_id) REFERENCES personalities.teachers(id);


--
-- Name: university_subjects university_subjects_universities_data_id_fk; Type: FK CONSTRAINT; Schema: subjects; Owner: max_superuser
--

ALTER TABLE ONLY subjects.university_subjects
    ADD CONSTRAINT university_subjects_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);


--
-- Name: courses courses_university_departments_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.courses
    ADD CONSTRAINT courses_university_departments_id_fk FOREIGN KEY (university_department_id) REFERENCES universities.university_departments(id);


--
-- Name: faculties faculties_universities_data_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.faculties
    ADD CONSTRAINT faculties_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);


--
-- Name: universities_data universities_data_cities_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.universities_data
    ADD CONSTRAINT universities_data_cities_id_fk FOREIGN KEY (city_id) REFERENCES universities.cities(id);


--
-- Name: university_departments university_departments_departments_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.university_departments
    ADD CONSTRAINT university_departments_departments_id_fk FOREIGN KEY (department_id) REFERENCES universities.departments(id);


--
-- Name: university_departments university_departments_faculties_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.university_departments
    ADD CONSTRAINT university_departments_faculties_id_fk FOREIGN KEY (faculty_id) REFERENCES universities.faculties(id);


--
-- Name: university_departments university_departments_universities_data_id_fk; Type: FK CONSTRAINT; Schema: universities; Owner: max_superuser
--

ALTER TABLE ONLY universities.university_departments
    ADD CONSTRAINT university_departments_universities_data_id_fk FOREIGN KEY (university_id) REFERENCES universities.universities_data(id);
--
-- NAME: refresh_tokens
--

CREATE TABLE users.refresh_tokens (
    id BIGINT NOT NULL,
    max_user_id BIGINT,
    token varchar(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (token)
);

ALTER TABLE users.refresh_tokens OWNER TO max_superuser;

ALTER TABLE users.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY users.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users.refresh_tokens
    ADD CONSTRAINT refresh_tokens_max_user_data_id_fk FOREIGN KEY (max_user_id) REFERENCES users.max_users_data(id);

CREATE TYPE users.ROLE_TYPE AS ENUM ('administration', 'student', 'teacher');

CREATE TABLE users.persons_adds (
                                    id BIGINT NOT NULL,
                                    from_max_user_id BIGINT NOT NULL,
                                    to_administration_id BIGINT NOT NULL,
                                    role_type users.ROLE_TYPE NOT NULL,
                                    UNIQUE (from_max_user_id, to_administration_id, role_type),
                                    FOREIGN KEY (from_max_user_id) REFERENCES users.max_users_data(id),
                                    FOREIGN KEY (to_administration_id) REFERENCES personalities.administrations(id)
);

ALTER TABLE users.refresh_tokens OWNER TO max_superuser;
ALTER TABLE users.persons_adds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users.persons_adds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY users.persons_adds
    ADD CONSTRAINT persons_adds_pkey PRIMARY KEY (id);
--
-- PostgreSQL database dump complete
--

