// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/department": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new department for a specific faculty and university. Admin role required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create new department",
                "parameters": [
                    {
                        "description": "Department data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateDepartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: department created successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not admin",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/admin/faculties": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new faculty. Requires admin role. The faculty will be associated with the university of the current admin user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "faculties"
                ],
                "summary": "Create new faculty",
                "parameters": [
                    {
                        "description": "Faculty creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateNewFacultyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Faculty created successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing or invalid token",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not admin",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/admin/groups": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new group for a specific department, faculty and university. Admin role required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create new group",
                "parameters": [
                    {
                        "description": "Group data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: group created successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing required fields",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not admin",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/admin/personalities/access": {
            "get": {
                "description": "Current authenticated user sends a request to get a access requests to be in university (student/teacher/administration).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "get all requests access for administration of university",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit of requests max(50), default(5)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "offset default(0)",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requests for administration",
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.AccessRequestResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Current authenticated user sends a request to get a role in a university (student/teacher/administration).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Request access to join a university",
                "parameters": [
                    {
                        "description": "Access request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.RequestAccessToUniversity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "decline access request for user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "reject access request",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "request_id",
                        "name": "request_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/admin/personalities/access/accept": {
            "post": {
                "description": "Accept Request of user that want to be (student/teacher/administration), for student field university_department_id is required, course_group_id can be skipped. For administrations university_id is required, faculty_id can be skipped",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Accept Request for adding in University",
                "parameters": [
                    {
                        "description": "Access request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.AcceptAccessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/departments": {
            "get": {
                "description": "Get all departments for faculty by faculty ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all departments for faculty",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Faculty ID",
                        "name": "faculty_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Departments",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.DepartmentInfoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameter",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/faculty": {
            "get": {
                "description": "Get all faculties for university by university ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all faculties for university",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "University ID",
                        "name": "university_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Faculties",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.FacultyInfoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameter",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/groups": {
            "get": {
                "description": "Get all course groups for department by department ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all groups for department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Groups",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.GroupInfoResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameter",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/student": {
            "get": {
                "description": "Get all students for course group by group ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all students for group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course Group ID",
                        "name": "group_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Students",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameter",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/teachers": {
            "get": {
                "description": "Get all teachers for university by university ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all teachers for university",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "University ID",
                        "name": "university_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Teachers",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request parameter",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/personalities/universities": {
            "get": {
                "description": "Get all universities where the authenticated user has access (as admin or student)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalities"
                ],
                "summary": "Get all universities for authenticated person",
                "responses": {
                    "200": {
                        "description": "Universities",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.UniInfoResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "description": "get all subjects for university by university ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "get all subjects by university ID",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "limit of requests max(50), default(5)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "offset default(0)",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Requests for administration",
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_http_subjects.SubjectsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "handler that provide creation of subject for university",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "create subject for university",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_http_subjects.CreateSubjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            },
            "delete": {
                "description": "get subject by subject ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "delete subject",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "subject ID",
                        "name": "subject_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/universities/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all universities with their detailed information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universities"
                ],
                "summary": "Get all universities",
                "responses": {
                    "200": {
                        "description": "List of universities",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.UniInfoResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error - failed to get universities",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/universities/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed information about the university associated with the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universities"
                ],
                "summary": "Get university information for current user",
                "responses": {
                    "200": {
                        "description": "University information",
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.UniInfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - user not authenticated",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error - failed to get university info",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        },
        "/universities/semesters": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create or replace semester periods for specific university. Admin role required. This operation will delete all existing semesters for the university and create new ones.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "universities"
                ],
                "summary": "Create new semester periods for university",
                "parameters": [
                    {
                        "description": "Semester periods data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateSemestersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: semesters created successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request body or date format",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized user",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - user is not admin",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateDepartmentRequest": {
            "type": "object",
            "required": [
                "department_name",
                "faculty_id",
                "university_id"
            ],
            "properties": {
                "department_name": {
                    "type": "string"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "university_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateGroupRequest": {
            "type": "object",
            "required": [
                "department_id",
                "faculty_id",
                "group_name",
                "university_id"
            ],
            "properties": {
                "department_id": {
                    "type": "integer"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "group_name": {
                    "type": "string"
                },
                "university_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateNewFacultyRequest": {
            "type": "object",
            "required": [
                "faculty_name"
            ],
            "properties": {
                "faculty_name": {
                    "type": "string",
                    "example": "FITIP"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.CreateSemestersRequest": {
            "type": "object",
            "required": [
                "periods",
                "uni_id"
            ],
            "properties": {
                "periods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.SemesterPeriod"
                    }
                },
                "uni_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.DepartmentInfoResponse": {
            "type": "object",
            "required": [
                "code",
                "department_name",
                "faculty_name",
                "id"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "09.03.02"
                },
                "department_name": {
                    "type": "string",
                    "example": "Sowtware Engineering"
                },
                "faculty_name": {
                    "type": "string",
                    "example": "FITIP"
                },
                "id": {
                    "type": "integer",
                    "example": 123456789
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.FacultyInfoResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "university_name": {
                    "type": "string"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.GroupInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "department_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.SemesterPeriod": {
            "type": "object",
            "required": [
                "end_date",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2006-12-23T00:00:00Z"
                },
                "start_date": {
                    "type": "string",
                    "example": "2005-12-23T00:00:00Z"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.UniInfoResponse": {
            "type": "object",
            "required": [
                "city",
                "id",
                "uni_name"
            ],
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Saint-Petersburg"
                },
                "description": {
                    "type": "string",
                    "example": "One of the leading Russian universities in the field of information technology, optical design, and engineering."
                },
                "id": {
                    "type": "integer",
                    "example": 123456789
                },
                "photo_url": {
                    "type": "string",
                    "example": "https://itmo.ru/images/itmo.jpg"
                },
                "site_url": {
                    "type": "string",
                    "example": "https://itmo.ru"
                },
                "uni_name": {
                    "type": "string",
                    "example": "ITMO University"
                },
                "uni_short_name": {
                    "type": "string",
                    "example": "ITMO"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_http_dto.User": {
            "type": "object",
            "required": [
                "first_name",
                "id"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "type": "integer",
                    "example": 123456789
                },
                "language_code": {
                    "type": "string",
                    "example": "ru"
                },
                "last_name": {
                    "type": "string",
                    "example": "Doe"
                },
                "photo_url": {
                    "type": "string",
                    "example": "https://example.com/photo.jpg"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.AcceptAccessRequest": {
            "type": "object",
            "required": [
                "role",
                "user_id"
            ],
            "properties": {
                "course_group_id": {
                    "type": "integer"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_repository_personalities.RoleType"
                },
                "university_department_id": {
                    "type": "integer"
                },
                "university_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.AccessRequestResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "first_name": {
                                "type": "string"
                            },
                            "last_name": {
                                "type": "string"
                            },
                            "request_id": {
                                "type": "integer"
                            },
                            "role": {
                                "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_repository_personalities.RoleType"
                            },
                            "user_id": {
                                "type": "integer"
                            },
                            "username": {
                                "type": "string"
                            }
                        }
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_http_personalities.RequestAccessToUniversity": {
            "type": "object",
            "properties": {
                "role": {
                    "$ref": "#/definitions/github_com_max-main-team_backend_hackaton_MAX_internal_models_repository_personalities.RoleType"
                },
                "university_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_http_subjects.CreateSubjectRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "university_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_http_subjects.SubjectsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "has_more": {
                    "type": "boolean"
                }
            }
        },
        "github_com_max-main-team_backend_hackaton_MAX_internal_models_repository_personalities.RoleType": {
            "type": "string",
            "enum": [
                "student",
                "teacher",
                "administration"
            ],
            "x-enum-varnames": [
                "Student",
                "Teacher",
                "Admin"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hackaton API",
	Description:      "API for Hackaton backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
